import { StyleSheet } from "react-native";
export const colors = {
  bg: "#121110",
  panel: "#191817",
  panel2: "#242121",
  text: "#f2eded",
  muted: "#98938f",
  line: "#343230",
  accent: "#f2eded",
  danger: "#b75d54",
  blue: "#b9c7d0",
};
export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg },
  safe: { flex: 1, paddingHorizontal: 20 },
  title: {
    color: colors.text,
    fontSize: 24,
    fontWeight: "700",
    letterSpacing: -0.8,
  },
  eyebrow: {
    color: colors.muted,
    fontSize: 13,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  subtitle: { color: colors.muted, fontSize: 14, lineHeight: 20 },
  input: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 10,
    color: colors.text,
    padding: 14,
    fontSize: 16,
  },
  button: {
    backgroundColor: colors.accent,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 13,
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: { color: "#191817", fontWeight: "700", fontSize: 15 },
  ghost: {
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    minHeight: 48,
    alignItems: "center",
  },
  ghostText: { color: colors.text, fontWeight: "600" },
  card: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 14,
    padding: 15,
  },
  cardPressable: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 14,
    padding: 15,
    minHeight: 56,
  },
  navItem: {
    flex: 1,
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
  },
  navLabel: { fontSize: 12, fontWeight: "600" },
  label: { color: colors.muted, fontSize: 12, marginBottom: 7 },
  error: { color: colors.danger, marginTop: 10, lineHeight: 19 },
});
