import { StyleSheet } from "react-native";
export const colors = {
  bg: "#111313",
  panel: "#181b1b",
  panel2: "#202424",
  text: "#f0f1ec",
  muted: "#9b9f99",
  line: "#303533",
  accent: "#d7f26b",
  danger: "#f08b83",
  blue: "#9fd5ff",
};
export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg },
  safe: { flex: 1, paddingHorizontal: 20 },
  title: {
    color: colors.text,
    fontSize: 30,
    fontWeight: "700",
    letterSpacing: -0.8,
  },
  eyebrow: {
    color: colors.muted,
    fontSize: 13,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  subtitle: { color: colors.muted, fontSize: 14, lineHeight: 20 },
  input: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 10,
    color: colors.text,
    padding: 14,
    fontSize: 16,
  },
  button: {
    backgroundColor: colors.accent,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 13,
    alignItems: "center",
  },
  buttonText: { color: "#141712", fontWeight: "700", fontSize: 15 },
  ghost: {
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    alignItems: "center",
  },
  ghostText: { color: colors.text, fontWeight: "600" },
  card: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 14,
    padding: 15,
  },
  label: { color: colors.muted, fontSize: 12, marginBottom: 7 },
  error: { color: colors.danger, marginTop: 10, lineHeight: 19 },
});
