import { createHash } from "node:crypto";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { buildBundle } from "../scripts/release/build-bundle.mjs";

describe("release update bundle", () => {
  it("records verifiable worker and asset bytes without deployment secrets", async () => {
    const root = await mkdtemp(join(tmpdir(), "opencode-bundle-"));
    const worker = join(root, "worker");
    const assets = join(root, "assets");
    const output = join(root, "app-bundle.json");
    await mkdir(worker);
    await mkdir(join(assets, "static"), { recursive: true });
    await writeFile(join(worker, "index.js"), "export default { fetch() { return new Response('ok') } };\n");
    await writeFile(join(worker, "chunk.js"), "export const answer = 42;\n");
    await writeFile(join(worker, "index.js.map"), "{}\n");
    await writeFile(join(worker, "README.md"), "generated by Wrangler\n");
    await writeFile(join(assets, "static", "app.js"), "console.log('app');\n");

    const bundle = await buildBundle({
      output,
      workerDirectory: worker,
      assetsDirectory: assets,
      version: "v1.2.3",
      commit: "a".repeat(40),
      imageReference: `docker.io/example/opencode-bot@sha256:${"b".repeat(64)}`,
      imageDigest: `sha256:${"b".repeat(64)}`,
      skipBuild: true,
    });
    expect(bundle.schemaVersion).toBe(1);
    expect(bundle.worker.mainModule).toBe("index.js");
    expect(bundle.worker.modules.every(module => module.contentType === "application/javascript+module")).toBe(true);
    expect(bundle.worker.modules.map((module) => module.name)).toEqual(["chunk.js", "index.js"]);
    expect(bundle.worker.metadata).toEqual({ assets: { config: { not_found_handling: "single-page-application", run_worker_first: ["/api/*", "/internal/*"] } } });
    const app = bundle.assets.find((asset) => asset.path === "static/app.js");
    expect(app).toBeDefined();
    const decoded = Buffer.from(app!.contentBase64, "base64");
    expect(decoded.byteLength).toBe(app!.size);
    expect(createHash("sha256").update(decoded).digest("hex")).toBe(app!.sha256);
    expect(JSON.stringify(bundle)).not.toMatch(/accountId|bucket_name|secret|token/i);
    expect(JSON.parse(await readFile(output, "utf8"))).toEqual(bundle);
  });

  it("rejects mutable or non-Docker image references", async () => {
    const root = await mkdtemp(join(tmpdir(), "opencode-bundle-invalid-"));
    await mkdir(join(root, "worker"));
    await mkdir(join(root, "assets"));
    await writeFile(join(root, "worker", "index.js"), "export default {};\n");
    await expect(buildBundle({
      output: join(root, "bundle.json"), workerDirectory: join(root, "worker"), assetsDirectory: join(root, "assets"),
      version: "v1.2.3", commit: "a".repeat(40), imageReference: "docker.io/example/opencode-bot:latest", imageDigest: "sha256:" + "b".repeat(64), skipBuild: true,
    })).rejects.toThrow(/immutable Docker Hub/);
  });
});
