param([string]$ControlUrl,[string]$PairingToken,[string]$Name,[string]$Version=$env:OCBOT_VERSION,[switch]$Uninstall)
$ErrorActionPreference = 'Stop'
$base = if ($env:OCBOT_RELEASE_BASE) { $env:OCBOT_RELEASE_BASE } else { 'https://github.com/pkyanam/opencode-bot' }
$root = if ($env:OCBOT_NODE_HOME) { $env:OCBOT_NODE_HOME } else { Join-Path $env:LOCALAPPDATA 'opencode-bot-node' }
$configDir = if ($env:OCBOT_NODE_CONFIG_DIR) { $env:OCBOT_NODE_CONFIG_DIR } else { Join-Path $env:APPDATA 'opencode-bot-node' }
$config = if ($env:OCBOT_NODE_CONFIG) { $env:OCBOT_NODE_CONFIG } else { Join-Path $configDir 'node.json' }
function Stop-Node { schtasks /End /TN 'OpenCode Bot Node' 2>$null | Out-Null; schtasks /Delete /TN 'OpenCode Bot Node' /F 2>$null | Out-Null }
if ($Uninstall) { Stop-Node; if (Test-Path (Join-Path $root '.opencode-bot-node-owned')) { Remove-Item -Recurse -Force $root } else { Write-Output "Preserving $root because its ownership marker is missing." }; if (Test-Path (Join-Path $configDir '.opencode-bot-node-owned')) { Remove-Item -Force $config,$(Join-Path $configDir '.opencode-bot-node-owned') -ErrorAction SilentlyContinue; Remove-Item -Recurse -Force (Join-Path $configDir 'state'),(Join-Path $configDir 'workspace') -ErrorAction SilentlyContinue } else { Write-Output "Preserving $configDir because its ownership marker is missing." }; Write-Output 'Node removed; revoke it in Settings if it is still listed.'; exit 0 }
if (!$ControlUrl -or !$PairingToken -or !$Name) { throw 'ControlUrl, PairingToken, and Name are required.' }
$tmp = Join-Path ([IO.Path]::GetTempPath()) ('opencode-node-' + [guid]::NewGuid()); New-Item -ItemType Directory -Path $tmp | Out-Null
try {
  $nodeVersion = if ($env:OCBOT_NODE_VERSION) { $env:OCBOT_NODE_VERSION } else { '24.14.0' }; $nodeRoot = Join-Path $root "node-v$nodeVersion"; $node = Join-Path $nodeRoot 'node.exe'; $systemNode = Get-Command node.exe -ErrorAction SilentlyContinue; $systemNpm = Get-Command npm.cmd -ErrorAction SilentlyContinue
  if (!$systemNode -or !$systemNpm -or (& $systemNode.Source -p 'Number(process.versions.node.split(".")[0])') -lt 24) {
    $arch = if ([Environment]::Is64BitOperatingSystem) { 'x64' } else { 'x86' }; $zip = "node-v$nodeVersion-win-$arch.zip"; Invoke-WebRequest "https://nodejs.org/dist/v$nodeVersion/$zip" -OutFile (Join-Path $tmp $zip); Invoke-WebRequest "https://nodejs.org/dist/v$nodeVersion/SHASUMS256.txt" -OutFile (Join-Path $tmp 'SHASUMS256.txt'); $line=(Get-Content (Join-Path $tmp 'SHASUMS256.txt') | Where-Object { $_ -match " $([regex]::Escape($zip))$" }); if ((Get-FileHash (Join-Path $tmp $zip) -Algorithm SHA256).Hash.ToLower() -ne $line.Split(' ')[0].ToLower()) { throw 'Node.js checksum verification failed' }; Expand-Archive (Join-Path $tmp $zip) -DestinationPath $tmp; New-Item -ItemType Directory -Force -Path $root | Out-Null; Remove-Item -Recurse -Force $nodeRoot -ErrorAction SilentlyContinue; Move-Item (Join-Path $tmp ([IO.Path]::GetFileNameWithoutExtension($zip))) $nodeRoot
  } else { $node = $systemNode.Source }
  $manifestUrl = if ($Version) { "$base/releases/download/$Version/node-bundle-manifest.json" } else { "$base/releases/latest/download/node-bundle-manifest.json" }; Invoke-WebRequest $manifestUrl -OutFile (Join-Path $tmp 'manifest.json'); $m=Get-Content (Join-Path $tmp 'manifest.json') | ConvertFrom-Json; if ($m.schemaVersion -ne 1 -or $m.archive.file -ne 'node-bundle.tar.gz' -or $m.archive.sha256 -notmatch '^[0-9a-f]{64}$') { throw 'Invalid node release manifest' }; $archive=Join-Path $tmp 'node-bundle.tar.gz'; Invoke-WebRequest "$base/releases/download/$($m.version)/node-bundle.tar.gz" -OutFile $archive; if ((Get-FileHash $archive -Algorithm SHA256).Hash.ToLower() -ne $m.archive.sha256.ToLower()) { throw 'Node bundle checksum verification failed' }
  if ((Get-Item $archive).Length -ne [int64]$m.archive.size) { throw 'Node bundle size verification failed' }; $bundle=Join-Path $root 'bundle'; New-Item -ItemType Directory -Force -Path $root | Out-Null; Remove-Item -Recurse -Force $bundle -ErrorAction SilentlyContinue; tar -xzf $archive -C $root; New-Item -ItemType File -Force -Path (Join-Path $root '.opencode-bot-node-owned') | Out-Null; $bundle=Join-Path $root 'bundle'; npm.cmd ci --prefix (Join-Path $bundle 'runner') --omit=dev --no-audit --fund=$false | Out-Null; if ($LASTEXITCODE -ne 0) { throw 'Runner dependency installation failed' }; New-Item -ItemType Junction -Path (Join-Path $bundle 'node_modules') -Target (Join-Path $bundle 'runner/node_modules') -Force | Out-Null; New-Item -ItemType Directory -Force -Path $configDir | Out-Null; & $node (Join-Path $bundle 'scripts/node-agent.mjs') register --control-url $ControlUrl --pairing-token $PairingToken --name $Name --config $config | Out-Null; if ($LASTEXITCODE -ne 0) { throw 'Node registration failed' }; New-Item -ItemType File -Force -Path (Join-Path $configDir '.opencode-bot-node-owned') | Out-Null
  $action = New-ScheduledTaskAction -Execute $node -Argument "`"$(Join-Path $bundle 'scripts/node-agent.mjs')`" start --config `"$config`""; Register-ScheduledTask -TaskName 'OpenCode Bot Node' -Action $action -Trigger (New-ScheduledTaskTrigger -AtLogOn) -Description 'OpenCode Bot outbound owned computer node' -Force | Out-Null; Start-ScheduledTask -TaskName 'OpenCode Bot Node'; Write-Output "Paired $Name and started the node service."
} finally { Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue }
